### ISSUE TITLE
Transition from Google Maps to OpenStreetMap for Venue Location on Website

### ISSUE THREAD

**Issue by SatyaRajAwasth1** [noskofficial/sfd-2023#2]
Google map is nice tool to have in our website for showing venue. 

In order to promote open source tool and our commitment of making people use and implement FOSS adding OSM as location tool will be really nice.

![image](https://github.com/noskofficial/sfd-2023/assets/77236280/311bfe3c-c2f0-4f38-ac5f-25ba24e1696a)

**Comment by Bibekdhkl** [comment]
Awesome!

**Comment by Bibekdhkl** [comment]
@SatyaRajAwasth1  Please look at #4 and fix that
